version: '3.8'

services:
  fastapi-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_qa_assistant
    ports:
      - "8501:8501"
    env_file:
      - .env
    volumes:
      - db_data:/app
    restart: unless-stopped

volumes:
  db_data:
